version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
